import { cacheGet,cacheSet,queueAdd,queueAll,queueRemove } from "./offline.js";
import { dateKey,escapeText,expandEvents,localInputValue,occupiedMetrics,recurrenceRule,reminderRows,startOfDay,startOfWeek,viewRange,DAY } from "./core.js";
import { apiUrl,getAuthContext,redirectToLogin } from "../auth/session.js";

const $=(id)=>document.getElementById(id);const locale="it-IT";
const state={supabase:null,user:null,session:null,events:[],visible:[],categories:[],preferences:null,anchor:new Date(),view:innerWidth<700?"day":"week",range:null,editing:null,loading:false};
const reminderChoices=[[0,"All’inizio"],[5,"5 minuti prima"],[10,"10 minuti prima"],[15,"15 minuti prima"],[30,"30 minuti prima"],[60,"1 ora prima"],[1440,"1 giorno prima"]];
const fmt=(date,options={})=>new Intl.DateTimeFormat(locale,{...options,timeZone:state.preferences?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone}).format(new Date(date));
function toast(message){$("toast").textContent=message;$("toast").classList.add("visible");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("visible"),2600);}
function setConnection(){const online=navigator.onLine;$("connectionBadge").textContent=online?"Online":"Offline";$("connectionBadge").classList.toggle("offline",!online);}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.session?.access_token)headers.Authorization=`Bearer ${state.session.access_token}`;const response=await fetch(apiUrl(path),{...options,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Operazione non riuscita");return body;}
async function boot(){try{const visual=JSON.parse(localStorage.getItem("aula-demo-layout-reale")||"{}");document.body.classList.toggle("light",!visual.dark);}catch{}setConnection();addEventListener("online",async()=>{setConnection();await flushQueue();await loadData();});addEventListener("offline",setConnection);if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
  try{const context=await getAuthContext();if(!context.session){redirectToLogin();return;}state.supabase=context.client;const config=await api("/api/agenda/config");state.vapidPublicKey=config.vapidPublicKey;await applySession(context.session);state.supabase.auth.onAuthStateChange((_event,session)=>{if(session)applySession(session);else redirectToLogin();});}
  catch(error){$("agendaApp").hidden=false;$("loadingState").hidden=false;$("loadingState").textContent=`Agenda non disponibile: ${error.message}`;}
}
async function applySession(session){state.session=session;state.user=session?.user||null;$("agendaApp").hidden=!state.user;$("mobileAddButton").hidden=!state.user;if(!state.user){redirectToLogin();return;}await state.supabase.rpc("ensure_calendar_defaults",{p_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC"});await loadData();await handleNotificationAction();}
async function handleNotificationAction(){const params=new URLSearchParams(location.search);const eventId=params.get("event"),action=params.get("notificationAction"),reminderId=params.get("reminder");if(!eventId)return;if(action==="complete")await state.supabase.from("calendar_events").update({status:"completed"}).eq("id",eventId).eq("user_id",state.user.id);else if(action==="snooze"&&reminderId)await state.supabase.from("event_reminders").update({status:"pending",scheduled_at:new Date(Date.now()+10*60000).toISOString(),sent_at:null}).eq("id",reminderId).eq("user_id",state.user.id);await loadData();const target=state.visible.find(e=>(e.series_event_id||e.id.split("@")[0])===eventId);if(target)openEvent(target.id);history.replaceState({},"","/agenda");}
async function loadData(){if(!state.user||state.loading)return;state.loading=true;$("loadingState").hidden=false;state.range=viewRange(state.view,state.anchor,state.preferences?.week_starts_on??1);const start=new Date(state.range.start.getTime()-DAY).toISOString(),end=new Date(state.range.end.getTime()+DAY).toISOString();
  try{const [events,categories,prefs]=await Promise.all([
    state.supabase.from("calendar_events").select("*,calendar_categories(name,color,icon)").eq("user_id",state.user.id).or(`and(starts_at.lt.${end},ends_at.gt.${start}),recurrence_rule.not.is.null`).limit(1000),
    state.supabase.from("calendar_categories").select("*").eq("user_id",state.user.id).order("name"),
    state.supabase.from("user_calendar_preferences").select("*").eq("user_id",state.user.id).single()
  ]);if(events.error)throw events.error;if(categories.error)throw categories.error;if(prefs.error)throw prefs.error;state.events=events.data;state.categories=categories.data;state.preferences=prefs.data;state.view=state.view||prefs.data.default_view;await cacheSet(`events:${state.user.id}`,state.events);await cacheSet(`categories:${state.user.id}`,state.categories);}
  catch(error){const cached=await cacheGet(`events:${state.user.id}`);const categories=await cacheGet(`categories:${state.user.id}`);if(cached){state.events=cached;state.categories=categories||[];toast("Offline: mostro gli ultimi dati sincronizzati");}else toast(error.message);}
  finally{state.loading=false;$("loadingState").hidden=true;render();}
}
function render(){state.range=viewRange(state.view,state.anchor,state.preferences?.week_starts_on??1);state.visible=expandEvents(state.events,state.range);renderPeriod();renderSwitcher();renderSummary();renderLegend();renderCalendar();$("datePicker").value=dateKey(state.anchor);}
function renderPeriod(){const opt=state.view==="day"?{weekday:"long",day:"numeric",month:"long",year:"numeric"}:state.view==="month"?{month:"long",year:"numeric"}:{day:"numeric",month:"long",year:"numeric"};$("periodTitle").textContent=state.view==="upcoming"?"Prossimi impegni":fmt(state.anchor,opt);}
function renderSwitcher(){document.querySelectorAll("[data-view]").forEach(b=>b.setAttribute("aria-selected",String(b.dataset.view===state.view)));}
function renderSummary(){const m=occupiedMetrics(state.visible,state.range);$("summary").innerHTML=[[m.count,"Eventi"],[m.occupiedHours.toFixed(1)+"h","Occupate"],[m.freeHours.toFixed(1)+"h","Libere"],[m.overlaps,"Sovrapp."]].map(([v,l])=>`<div class="summary-item"><strong>${v}</strong><span>${l}</span></div>`).join("");}
function renderLegend(){$("categoryLegend").innerHTML=state.categories.map(c=>`<div class="legend-item"><span class="color-dot" style="background:${c.color}"></span>${escapeText(c.name)}</div>`).join("");fillCategories();}
function eventCard(e){const color=e.color||e.calendar_categories?.color||"#22d3ee";return `<article class="calendar-event ${e.status==="completed"?"completed":""}" style="--event-color:${color}" data-event="${escapeText(e.id)}" tabindex="0" role="button" aria-label="${escapeText(e.title)}, ${fmt(e.starts_at,{hour:"2-digit",minute:"2-digit"})}"><strong>${escapeText(e.title)}</strong><span>${fmt(e.starts_at,{hour:"2-digit",minute:"2-digit"})}–${fmt(e.ends_at,{hour:"2-digit",minute:"2-digit"})}${e.location?` · ${escapeText(e.location)}`:""}</span></article>`;}
function renderCalendar(){if(state.view==="month")renderMonth();else if(state.view==="upcoming")renderUpcoming();else renderTimeGrid();bindEventCards();}
function renderTimeGrid(){const days=state.view==="day"?[startOfDay(state.anchor)]:Array.from({length:7},(_,i)=>new Date(state.range.start.getTime()+i*DAY));let html=`<div class="${state.view}-grid">`+`<div class="day-header"></div>`+days.map(d=>`<div class="day-header">${fmt(d,{weekday:"short",day:"numeric"})}</div>`).join("");for(let hour=0;hour<24;hour++){html+=`<div class="time-label">${String(hour).padStart(2,"0")}:00</div>`;for(const day of days){const cell=new Date(day);cell.setHours(hour);const matching=state.visible.filter(e=>new Date(e.starts_at).getHours()===hour&&dateKey(new Date(e.starts_at))===dateKey(day));html+=`<div class="time-slot" data-slot="${cell.toISOString()}">${matching.map(eventCard).join("")}</div>`;}}$("calendarView").innerHTML=html+"</div>";document.querySelectorAll("[data-slot]").forEach(c=>c.addEventListener("click",e=>{if(e.target===c)openNew(new Date(c.dataset.slot));}));}
function renderMonth(){const days=Array.from({length:42},(_,i)=>new Date(state.range.start.getTime()+i*DAY));const names=Array.from({length:7},(_,i)=>fmt(new Date(state.range.start.getTime()+i*DAY),{weekday:"short"}));$("calendarView").innerHTML=`<div class="month-grid">${names.map(n=>`<div class="month-weekday">${n}</div>`).join("")}${days.map(d=>`<div class="month-day ${d.getMonth()!==state.anchor.getMonth()?"outside":""} ${dateKey(d)===dateKey(new Date())?"today":""}"><button class="month-day-number" data-day="${d.toISOString()}">${d.getDate()}</button>${state.visible.filter(e=>dateKey(new Date(e.starts_at))===dateKey(d)).slice(0,4).map(eventCard).join("")}</div>`).join("")}</div>`;document.querySelectorAll("[data-day]").forEach(b=>b.onclick=()=>{state.anchor=new Date(b.dataset.day);state.view="day";loadData();});}
function renderUpcoming(){const groups=new Map();for(const e of state.visible){const key=dateKey(new Date(e.starts_at));if(!groups.has(key))groups.set(key,[]);groups.get(key).push(e);}$("calendarView").innerHTML=groups.size?`<div class="upcoming-list">${[...groups].map(([key,events])=>`<section class="upcoming-group"><h3>${fmt(new Date(key+"T12:00"),{weekday:"long",day:"numeric",month:"long"})}</h3>${events.map(e=>`<div class="upcoming-event"><strong>${fmt(e.starts_at,{hour:"2-digit",minute:"2-digit"})}</strong><div>${eventCard(e)}</div><button data-complete="${escapeText(e.id)}">Completa</button></div>`).join("")}</section>`).join("")}</div>`:`<div class="empty-state">Nessun impegno nei prossimi 90 giorni.</div>`;document.querySelectorAll("[data-complete]").forEach(b=>b.onclick=()=>completeEvent(b.dataset.complete));}
function bindEventCards(){document.querySelectorAll("[data-event]").forEach(el=>{const open=()=>openEvent(el.dataset.event);el.addEventListener("click",e=>{e.stopPropagation();open();});el.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open();}});});}
function realEvent(id){const base=id.split("@")[0];return state.events.find(e=>e.id===base)||state.events.find(e=>e.id===id);}
function fillCategories(){const select=$("eventCategory");const selected=select.value;select.innerHTML=state.categories.map(c=>`<option value="${c.id}">${escapeText(c.name)}</option>`).join("");if(selected)select.value=selected;}
function openNew(start=new Date()){state.editing=null;$("eventForm").reset();$("eventId").value="";$("eventDialogTitle").textContent="Nuovo evento";const rounded=new Date(start);rounded.setMinutes(Math.ceil(rounded.getMinutes()/15)*15,0,0);$("eventStart").value=localInputValue(rounded);$("eventEnd").value=localInputValue(new Date(rounded.getTime()+3600000));$("eventColor").value="#22d3ee";$("deleteEventButton").hidden=true;$("duplicateEventButton").hidden=true;fillCategories();const def=state.preferences?.default_reminder_minutes;document.querySelectorAll("[name=reminder]").forEach(c=>c.checked=Number(c.value)===def);$("eventDialog").showModal();$("eventTitle").focus();}
async function openEvent(id){const occurrence=state.visible.find(e=>e.id===id);const event=realEvent(id);if(!event)return;state.editing={event,occurrence};$("eventId").value=event.id;$("eventDialogTitle").textContent="Modifica evento";$("eventTitle").value=event.title;$("eventStart").value=localInputValue(new Date(occurrence?.starts_at||event.starts_at));$("eventEnd").value=localInputValue(new Date(occurrence?.ends_at||event.ends_at));$("eventAllDay").checked=event.all_day;$("eventCategory").value=event.category_id||"";$("eventColor").value=event.color||event.calendar_categories?.color||"#22d3ee";$("eventStatus").value=event.status;$("eventDescription").value=event.description||"";$("eventLocation").value=event.location||"";$("eventUrl").value=event.url||"";$("eventRecurrence").value=event.recurrence_rule?"custom":"";$("eventRrule").value=(event.recurrence_rule||"").split("RRULE:")[1]||"";$("rruleLabel").hidden=!event.recurrence_rule;const {data}=await state.supabase.from("event_reminders").select("offset_minutes").eq("event_id",event.id).in("status",["pending","failed"]);document.querySelectorAll("[name=reminder]").forEach(c=>c.checked=(data||[]).some(r=>r.offset_minutes===Number(c.value)));$("deleteEventButton").hidden=false;$("duplicateEventButton").hidden=false;$("eventDialog").showModal();$("eventTitle").focus();}
function eventPayload(){const start=new Date($("eventStart").value),end=new Date($("eventEnd").value);if(!$("eventTitle").value.trim())throw new Error("Inserisci un titolo");if(!(end>start))throw new Error("La fine deve essere successiva all’inizio");const kind=$("eventRecurrence").value;return{user_id:state.user.id,title:$("eventTitle").value.trim(),description:$("eventDescription").value.trim(),category_id:$("eventCategory").value||null,color:$("eventColor").value,location:$("eventLocation").value.trim(),url:$("eventUrl").value.trim()||null,starts_at:start.toISOString(),ends_at:end.toISOString(),all_day:$("eventAllDay").checked,timezone:state.preferences.timezone,status:$("eventStatus").value,recurrence_rule:recurrenceRule(kind,start,$("eventRrule").value,state.preferences.timezone)};}
function truncateRule(rule,before){const until=new Date(new Date(before).getTime()-1000).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const lines=String(rule).split("\n");const index=lines.findIndex(line=>line.startsWith("RRULE:"));if(index<0)return rule;const parts=lines[index].replace("RRULE:","").split(";").filter(part=>!part.startsWith("UNTIL=")&&!part.startsWith("COUNT="));lines[index]=`RRULE:${parts.join(";")};UNTIL=${until}`;return lines.join("\n");}
async function saveEvent(){const offsets=[...document.querySelectorAll("[name=reminder]:checked")].map(c=>Number(c.value));try{const payload=eventPayload();let data,error;if(state.editing){const parent=state.editing.event,occurrence=state.editing.occurrence;let scope="serie";if(parent.recurrence_rule&&occurrence)scope=prompt("Modificare: questo, successivi oppure serie", "questo")||"";if(scope==="questo"){payload.recurrence_rule=null;payload.recurrence_parent_id=parent.id;payload.recurrence_exception_date=dateKey(new Date(occurrence.starts_at));({data,error}=await state.supabase.from("calendar_events").insert(payload).select().single());}else if(scope==="successivi"){const cut=await state.supabase.from("calendar_events").update({recurrence_rule:truncateRule(parent.recurrence_rule,occurrence.starts_at)}).eq("id",parent.id).eq("user_id",state.user.id);if(cut.error)throw cut.error;({data,error}=await state.supabase.from("calendar_events").insert(payload).select().single());}else if(scope==="serie"){({data,error}=await state.supabase.from("calendar_events").update(payload).eq("id",parent.id).eq("user_id",state.user.id).eq("updated_at",parent.updated_at).select().single());if(!error)await state.supabase.from("event_reminders").delete().eq("event_id",data.id).in("status",["pending","failed"]);}else return;}else({data,error}=await state.supabase.from("calendar_events").insert(payload).select().single());if(error)throw error;if(offsets.length&&data.status!=="completed"){const rows=reminderRows(data,state.user.id,offsets);const reminder=await state.supabase.from("event_reminders").insert(rows);if(reminder.error)throw reminder.error;}$("eventDialog").close();toast("Evento sincronizzato");await loadData();}catch(error){if(!navigator.onLine){const payload=eventPayload();await queueAdd({kind:state.editing?"update":"insert",table:"calendar_events",id:state.editing?.event.id,payload,reminders:payload.status==="completed"?[]:offsets});if(state.editing)state.events=state.events.map(e=>e.id===state.editing.event.id?{...e,...payload}:e);else state.events.push({...payload,id:`offline-${crypto.randomUUID()}`,updated_at:new Date().toISOString()});await cacheSet(`events:${state.user.id}`,state.events);$("eventDialog").close();render();toast("Modifica in coda: sarà sincronizzata online");}else $("eventError").textContent=error.message.includes("0 rows")?"L’evento è stato modificato su un altro dispositivo. Aggiorna e riprova.":error.message;}}
async function deleteEvent(){if(!state.editing||!confirm("Eliminare questo evento?"))return;let id=state.editing.event.id;if(state.editing.event.recurrence_rule){const scope=prompt("Scrivi: questo, successivi oppure serie", "serie");if(scope==="questo"&&state.editing.occurrence){const override={...state.editing.event,id:undefined,recurrence_rule:null,recurrence_parent_id:id,recurrence_exception_date:dateKey(new Date(state.editing.occurrence.starts_at)),starts_at:state.editing.occurrence.starts_at,ends_at:state.editing.occurrence.ends_at,status:"cancelled"};delete override.calendar_categories;delete override.created_at;delete override.updated_at;await state.supabase.from("calendar_events").insert(override);$("eventDialog").close();await loadData();return;}if(scope==="successivi"&&state.editing.occurrence){await state.supabase.from("calendar_events").update({series_split_at:state.editing.occurrence.starts_at,recurrence_rule:truncateRule(state.editing.event.recurrence_rule,state.editing.occurrence.starts_at)}).eq("id",id).eq("user_id",state.user.id);$("eventDialog").close();await loadData();return;}}
  const {error}=await state.supabase.from("calendar_events").delete().eq("id",id).eq("user_id",state.user.id);if(error)return toast(error.message);$("eventDialog").close();toast("Evento eliminato");await loadData();}
async function completeEvent(id){const event=realEvent(id);if(!event)return;await state.supabase.from("calendar_events").update({status:"completed"}).eq("id",event.id).eq("user_id",state.user.id);await state.supabase.from("event_reminders").update({status:"cancelled"}).eq("event_id",event.id).in("status",["pending","failed"]);await loadData();}
async function duplicateEvent(){if(!state.editing)return;const payload=eventPayload();payload.title+= " (copia)";payload.recurrence_rule=null;const {data,error}=await state.supabase.from("calendar_events").insert(payload).select().single();if(error)return toast(error.message);$("eventDialog").close();toast("Evento duplicato");await loadData();}
async function flushQueue(){if(!state.supabase||!state.user)return;for(const item of await queueAll()){const query=item.kind==="insert"?state.supabase.from(item.table).insert(item.payload).select().single():state.supabase.from(item.table).update(item.payload).eq("id",item.id).eq("user_id",state.user.id).select().single();const {data,error}=await query;if(!error){if(item.reminders?.length&&data)await state.supabase.from("event_reminders").insert(reminderRows(data,state.user.id,item.reminders));await queueRemove(item.queueId);}}}
function movePeriod(direction){const d=new Date(state.anchor);if(state.view==="day")d.setDate(d.getDate()+direction);else if(state.view==="week")d.setDate(d.getDate()+7*direction);else d.setMonth(d.getMonth()+direction);state.anchor=d;loadData();}
async function savePreferences(){const payload={timezone:$("settingTimezone").value,week_starts_on:Number($("settingWeekStart").value),default_view:$("settingDefaultView").value,default_reminder_minutes:$("settingDefaultReminder").value===""?null:Number($("settingDefaultReminder").value),hour_format:Number($("settingHourFormat").value),quiet_hours_enabled:$("settingQuietEnabled").checked,quiet_hours_start:$("settingQuietStart").value,quiet_hours_end:$("settingQuietEnd").value,quiet_hours_behavior:$("settingQuietBehavior").value,hide_notification_details:$("settingHideDetails").checked};const {error}=await state.supabase.from("user_calendar_preferences").update(payload).eq("user_id",state.user.id);if(error){toast(error.message);return false;}toast("Impostazioni salvate");return true;}
async function openSettings(){const p=state.preferences;$("settingDefaultView").value=p.default_view;$("settingWeekStart").value=p.week_starts_on;$("settingTimezone").value=p.timezone;$("settingHourFormat").value=p.hour_format;$("settingDefaultReminder").value=p.default_reminder_minutes??"";$("settingQuietEnabled").checked=p.quiet_hours_enabled;$("settingQuietStart").value=String(p.quiet_hours_start).slice(0,5);$("settingQuietEnd").value=String(p.quiet_hours_end).slice(0,5);$("settingQuietBehavior").value=p.quiet_hours_behavior;$("settingHideDetails").checked=p.hide_notification_details;renderCategoryManager();await renderDevices();renderNotificationStatus();$("settingsDialog").showModal();}
function renderCategoryManager(){$("categoryManager").innerHTML=state.categories.map(c=>`<div class="category-row"><input type="color" value="${c.color}" data-cat-color="${c.id}" aria-label="Colore ${escapeText(c.name)}"><input value="${escapeText(c.name)}" maxlength="40" data-cat-name="${c.id}" aria-label="Nome categoria"><label class="check-label"><input type="radio" name="defaultCategory" value="${c.id}" ${c.is_default?"checked":""}>Predefinita</label><button type="button" data-cat-delete="${c.id}" class="danger">Elimina</button></div>`).join("");document.querySelectorAll("[data-cat-name],[data-cat-color]").forEach(i=>i.onchange=()=>updateCategory(i.dataset.catName||i.dataset.catColor));document.querySelectorAll("[name=defaultCategory]").forEach(i=>i.onchange=()=>setDefaultCategory(i.value));document.querySelectorAll("[data-cat-delete]").forEach(b=>b.onclick=()=>deleteCategory(b.dataset.catDelete));}
async function updateCategory(id){const name=document.querySelector(`[data-cat-name="${id}"]`).value.trim(),color=document.querySelector(`[data-cat-color="${id}"]`).value;await state.supabase.from("calendar_categories").update({name,color}).eq("id",id).eq("user_id",state.user.id);await loadData();renderCategoryManager();}
async function setDefaultCategory(id){await state.supabase.from("calendar_categories").update({is_default:false}).eq("user_id",state.user.id);await state.supabase.from("calendar_categories").update({is_default:true}).eq("id",id).eq("user_id",state.user.id);await loadData();renderCategoryManager();}
async function addCategory(){const name=prompt("Nome della nuova categoria");if(!name)return;const {error}=await state.supabase.from("calendar_categories").insert({user_id:state.user.id,name:name.trim(),color:"#22d3ee"});if(error)toast(error.message);else{await loadData();renderCategoryManager();}}
async function deleteCategory(id){if(state.categories.length<2)return toast("Deve restare almeno una categoria");const replacement=state.categories.find(c=>c.id!==id&&c.name==="Altro")||state.categories.find(c=>c.id!==id);if(!confirm(`Gli eventi saranno assegnati a ${replacement.name}. Continuare?`))return;const {error}=await state.supabase.rpc("reassign_and_delete_category",{p_category:id,p_replacement:replacement.id});if(error)toast(error.message);else{await loadData();renderCategoryManager();}}
async function renderDevices(){try{const {subscriptions}=await api("/api/agenda/subscriptions");$("deviceManager").innerHTML=subscriptions.length?subscriptions.map(s=>`<div class="device-row"><span>◉</span><span>${escapeText(s.device_name)}<small>${s.enabled?" Attivo":" Disattivato"}</small></span><button type="button" data-device-off="${s.id}">Disattiva</button></div>`).join(""):"<p>Nessun dispositivo registrato.</p>";document.querySelectorAll("[data-device-off]").forEach(b=>b.onclick=async()=>{await api(`/api/agenda/subscriptions?id=${b.dataset.deviceOff}`,{method:"DELETE"});renderDevices();});}catch(e){$("deviceManager").textContent=e.message;}}
function renderNotificationStatus(){let text="Autorizzazione non ancora richiesta";if(!("Notification" in window)||!("PushManager" in window))text="Notifiche non supportate";else if(Notification.permission==="granted")text="Notifiche autorizzate";else if(Notification.permission==="denied")text="Notifiche bloccate nelle impostazioni del dispositivo";$("notificationStatus").textContent=text;const iosWebAppCapable="standalone" in navigator;const installed=navigator.standalone===true||matchMedia("(display-mode: standalone)").matches;$("iosHelp").hidden=!(iosWebAppCapable&&!installed);}
function base64ToBytes(value){const padding="=".repeat((4-value.length%4)%4);const raw=atob((value+padding).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));}
async function enableNotifications(){if(!("serviceWorker" in navigator)||!("PushManager" in window))return toast("Notifiche non supportate");const permission=await Notification.requestPermission();if(permission!=="granted"){renderNotificationStatus();return;}const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64ToBytes(state.vapidPublicKey)});await api("/api/agenda/subscriptions",{method:"POST",body:JSON.stringify({...subscription.toJSON(),deviceName:navigator.platform||"Dispositivo"})});await state.supabase.from("user_calendar_preferences").update({notifications_enabled:true}).eq("user_id",state.user.id);state.preferences.notifications_enabled=true;renderNotificationStatus();renderDevices();toast("Notifiche attive");}
async function loadDemo(){if(!confirm("Caricare il programma di esempio nella settimana corrente?"))return;const monday=startOfWeek(state.anchor,1),studio=state.categories.find(c=>c.name==="Studio"),lavoro=state.categories.find(c=>c.name==="Lavoro"),personale=state.categories.find(c=>c.name==="Personale");const rows=[];for(let i=0;i<7;i++){const day=new Date(monday.getTime()+i*DAY);const add=(title,h1,h2,cat,description="")=>{const s=new Date(day);s.setHours(h1,0,0,0);const e=new Date(day);e.setHours(h2,0,0,0);rows.push({user_id:state.user.id,title,description,category_id:cat?.id,starts_at:s.toISOString(),ends_at:e.toISOString(),timezone:state.preferences.timezone,status:"confirmed"});};if(i<2)add("Samira",17,18,personale);else{add("Sessione di studio",8,13,studio);add("Lavoro",13,22,lavoro);if(i<4)add("Chiamata con i fratelli",22,23,personale,"Studio / intrattenimento");}}const {error}=await state.supabase.from("calendar_events").insert(rows);if(error)toast(error.message);else{toast("Programma di esempio caricato");await loadData();}}
function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),events:state.events,categories:state.categories,preferences:state.preferences},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`aula-agenda-${dateKey(new Date())}.json`;a.click();URL.revokeObjectURL(a.href);}
async function deleteAll(){if(!confirm("Eliminare definitivamente tutti i dati dell’Agenda?"))return;const check=prompt("Scrivi ELIMINA per confermare");if(check!=="ELIMINA")return;const {error}=await state.supabase.rpc("delete_my_calendar_data");if(error)toast(error.message);else{toast("Dati eliminati");await state.supabase.rpc("ensure_calendar_defaults",{p_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});await loadData();}}
function bind(){$("reminderOptions").innerHTML=reminderChoices.map(([v,l])=>`<label><input type="checkbox" name="reminder" value="${v}">${l}</label>`).join("");$("newEventButton").onclick=()=>openNew();$("mobileAddButton").onclick=()=>openNew();$("previousButton").onclick=()=>movePeriod(-1);$("nextButton").onclick=()=>movePeriod(1);$("todayButton").onclick=()=>{state.anchor=new Date();loadData();};$("datePicker").onchange=()=>{state.anchor=new Date($("datePicker").value+"T12:00");loadData();};$("viewSwitcher").onclick=e=>{if(e.target.dataset.view){state.view=e.target.dataset.view;loadData();}};document.querySelectorAll(".close-dialog").forEach(b=>b.onclick=()=>b.closest("dialog").close());$("eventForm").onsubmit=e=>{e.preventDefault();saveEvent();};$("deleteEventButton").onclick=deleteEvent;$("duplicateEventButton").onclick=duplicateEvent;$("eventRecurrence").onchange=()=>$("rruleLabel").hidden=$("eventRecurrence").value!=="custom";$("settingsButton").onclick=openSettings;$("settingsForm").onsubmit=async e=>{e.preventDefault();if(await savePreferences()){$("settingsDialog").close();await loadData();}};$("enableNotifications").onclick=enableNotifications;$("testNotification").onclick=async()=>{try{await api("/api/agenda/test-notification",{method:"POST",body:"{}"});toast("Notifica di prova inviata");}catch(e){toast(e.message);}};$("addCategoryButton").onclick=addCategory;$("loadDemoButton").onclick=loadDemo;$("exportButton").onclick=exportData;$("deleteAllButton").onclick=deleteAll;}
bind();$("themeButton").onclick=()=>{document.body.classList.toggle("light");try{const visual=JSON.parse(localStorage.getItem("aula-demo-layout-reale")||"{}");visual.dark=!document.body.classList.contains("light");localStorage.setItem("aula-demo-layout-reale",JSON.stringify(visual));}catch{}};boot();
